
# Enable logging
logger:

ota:
  password: !secret iot_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

web_server:
  port: 80
  ota: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  
time:
  - platform: homeassistant
    id: homeassistant_time
    