esphome:
  name: miratest

esp8266:
  board: nodemcuv2

# Enable logging
logger:

ota:
  password: !secret iot_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

web_server:
  port: 80
  ota: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  
time:
  - platform: homeassistant
    id: homeassistant_time
    
# Example configuration entry
display:
    platform: tm1638
    id: tm1638_display
    stb_pin: D3
    clk_pin: D2
    dio_pin: D1
    intensity: 1
    update_interval: 500ms
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());
      
      it.printf(4, "%02.1f", id(envtemperature).state);

switch:
  - platform: tm1638
    id: TM1638Led1
    led: 0
    name: "LED 1"
  - platform: tm1638
    id: TM1638Led2
    led: 1
    name: "LED 2"
  - platform: tm1638
    id: TM1638Led3
    led: 2
    name: "LED 3"
  - platform: tm1638
    id: TM1638Led4
    led: 3
    name: "LED 4"
  - platform: tm1638
    id: TM1638Led5
    led: 4
    name: "LED 5"

binary_sensor:
  - platform: gpio
    pin: D7
    id: Feuchtigkeitssensor
    name: Feuchtigkeitssensor

  - platform: tm1638
    name: "TM1638 Button 1"
    id: TM1638Button1
    key: 0
    filters:
      - delayed_on: 10ms

  - platform: tm1638
    name: "TM1638 Button 2"
    id: TM1638Button2
    key: 1
    filters:
      - delayed_on: 10ms
  - platform: tm1638
    name: "TM1638 Button 3"
    id: TM1638Button3
    key: 2
    filters:
      - delayed_on: 10ms
  - platform: tm1638
    name: "TM1638 Button 4"
    id: TM1638Button4
    key: 3
    filters:
      - delayed_on: 10ms
  - platform: tm1638
    name: "TM1638 Button 5"
    id: TM1638Button5
    key: 4
    filters:
      - delayed_on: 10ms


  - platform: tm1638
    id: TM1638Button8
    internal: true
    key: 7
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - number.increment: display_brightness

i2c:
  sda: D6
  scl: D5
  scan: true
  id: bus_a

#      D5 SCL
#      D6 SDA

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      id: envtemperature
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s
    id: envsensor

number:
  - platform: template
    name: "Display brightness"
    id: display_brightness
    min_value: 0
    max_value: 7
    step: 1
    optimistic: true
    set_action: 
      - lambda: |-
          id(tm1638_display).set_intensity(x);
