# control Dell P4317Q monitor via RS232


esphome:
    name: monitorcontrol

esp8266:
  board: esp01_1m

# Enable logging
logger:
  hardware_uart: UART1

ota:
  password: !secret iot_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

web_server:
  port: 80
  ota: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      timeout: 500ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, '.');

number:
  - platform: template
    name: "Monitor Brightness"
    id: brightness
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    set_action:
      - uart.write: !lambda
          return {0x37, 0x51, 0x03, 0xEA, 0x30, (int)x, 0x37^0x51^0x03^0xEA^0x30^(int)x};

button:
  - platform: template
    name: "Input HDMI1"
    on_press:
      - uart.write: [0x37, 0x51, 0x06, 0xEA, 0x62, 0x01, 0x00, 0x00, 0x00, 0xE9]
  - platform: template
    name: "Input HDMI2"
    on_press:
      - uart.write: [0x37, 0x51, 0x06, 0xEA, 0x62, 0x02, 0x00, 0x00, 0x00, 0xEA]
  - platform: template
    name: "Input DisplayPort"
    on_press:
      - uart.write: [0x37, 0x51, 0x06, 0xEA, 0x62, 0x08, 0x00, 0x00, 0x00, 0xE0]

switch:
  - platform: template
    name: "Monitor Power"
    optimistic: true
    turn_on_action:
      - uart.write: !lambda
          return {0x37, 0x51, 0x03, 0xEA, 0x20, 0x01, 0xAE};
    turn_off_action:
      - uart.write: !lambda
          return {0x37, 0x51, 0x03, 0xEA, 0x20, 0x00, 0xAF};
    
  - platform: uart
    name: "Test"
    data: [0x37, 0x51, 0x02, 0xEB, 0x01, 0x8E,
       0x37, 0x51, 0x02, 0xEB, 0x02, 0x8D,
        0x37, 0x51, 0x02, 0xEB, 0x47, 0xCC,
         0x37, 0x51, 0x02, 0xEB, 0x48, 0xCD ]

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: button1
    on_click:
      - then:
          - if:
              condition:
                number.in_range:
                  id: brightness
                  above: 50.0
              then:
                - number.set:
                    id: brightness
                    value: 0.0
              else:
                - number.set:
                    id: brightness
                    value: 100.0
  