esphome:
  name: pmsensor

esp8266:
  board: nodemcuv2
<<: !include _common.yaml
    
i2c:
  sda: D3
  scl: D4
  scan: true
  id: bus_a

#      D5 SCL
#      D6 SDA

sensor:
  - platform: bmp085
    temperature:
        name: "Outside Temperature"
    pressure:
        name: "Outside Pressure"
    update_interval: 60s
    id: envsensor

