esphome:
  name: pmsensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

ota:
  password: !secret iot_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

web_server:
  port: 80
  ota: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  
time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

    
i2c:
  sda: D3
  scl: D4
  scan: true
  id: bus_a

#      D5 SCL
#      D6 SDA

sensor:
  - platform: bmp085
    temperature:
        name: "Outside Temperature"
    pressure:
        name: "Outside Pressure"
    update_interval: 60s
    id: envsensor

